"""add oauth fields to user

Revision ID: 7bccb2b40fb6
Revises: b47b91689d38
Create Date: 2026-02-12 12:13:52.226952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bccb2b40fb6'
down_revision = 'b47b91689d38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('oauth_provider', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('oauth_id', sa.Text(), nullable=True))
        batch_op.alter_column('password_hash',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_users_oauth_id'), ['oauth_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_oauth_id'))
        batch_op.alter_column('password_hash',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('oauth_id')
        batch_op.drop_column('oauth_provider')

    # ### end Alembic commands ###
