"""initial

Revision ID: b47b91689d38
Revises: 
Create Date: 2026-02-11 17:02:38.379421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b47b91689d38'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('notification_preferences',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('trip_reminders', sa.Boolean(), nullable=True),
    sa.Column('price_alerts', sa.Boolean(), nullable=True),
    sa.Column('product_updates', sa.Boolean(), nullable=True),
    sa.Column('marketing_opt_in', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=True),
    sa.Column('provider_customer_id', sa.Text(), nullable=True),
    sa.Column('provider_subscription_id', sa.Text(), nullable=True),
    sa.Column('plan', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscriptions_user_id'), ['user_id'], unique=False)

    op.create_table('trips',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('destination', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('travelers_count', sa.Integer(), nullable=True),
    sa.Column('origin', sa.Text(), nullable=True),
    sa.Column('budget_tier', sa.Text(), nullable=True),
    sa.Column('pace', sa.Text(), nullable=True),
    sa.Column('interests_array', sa.Text(), nullable=True),
    sa.Column('constraints', sa.JSON(), nullable=True),
    sa.Column('must_do', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trips_user_id'), ['user_id'], unique=False)

    op.create_table('user_preferences',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('remember_preferences', sa.Boolean(), nullable=True),
    sa.Column('default_budget_tier', sa.Text(), nullable=True),
    sa.Column('default_pace', sa.Text(), nullable=True),
    sa.Column('default_home_city', sa.Text(), nullable=True),
    sa.Column('default_home_airport', sa.Text(), nullable=True),
    sa.Column('interests_array', sa.Text(), nullable=True),
    sa.Column('constraints', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('chat_threads',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('trip_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_threads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_threads_trip_id'), ['trip_id'], unique=False)

    op.create_table('flight_options',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('trip_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=True),
    sa.Column('deep_link_url', sa.Text(), nullable=True),
    sa.Column('price_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_currency', sa.Text(), nullable=True),
    sa.Column('depart_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('arrive_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('stops_count', sa.Integer(), nullable=True),
    sa.Column('airline', sa.Text(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('saved', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('flight_options', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_flight_options_trip_id'), ['trip_id'], unique=False)

    op.create_table('invoices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('subscription_id', sa.Uuid(), nullable=True),
    sa.Column('provider_invoice_id', sa.Text(), nullable=True),
    sa.Column('amount_paid', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.Text(), nullable=True),
    sa.Column('hosted_invoice_url', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoices_user_id'), ['user_id'], unique=False)

    op.create_table('notification_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('trip_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('delivery_status', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_events_trip_id'), ['trip_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_events_user_id'), ['user_id'], unique=False)

    op.create_table('price_alerts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('trip_id', sa.Uuid(), nullable=True),
    sa.Column('alert_type', sa.Text(), nullable=True),
    sa.Column('threshold_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('threshold_currency', sa.Text(), nullable=True),
    sa.Column('route', sa.JSON(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('price_alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_price_alerts_trip_id'), ['trip_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_price_alerts_user_id'), ['user_id'], unique=False)

    op.create_table('stay_options',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('trip_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=True),
    sa.Column('deep_link_url', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('neighborhood', sa.Text(), nullable=True),
    sa.Column('rating', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('price_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_currency', sa.Text(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('why_it_fits', sa.Text(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('saved', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stay_options', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stay_options_trip_id'), ['trip_id'], unique=False)

    op.create_table('trip_days',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('trip_id', sa.Uuid(), nullable=False),
    sa.Column('day_index', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trip_days', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trip_days_trip_id'), ['trip_id'], unique=False)

    op.create_table('trip_generation_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('trip_id', sa.Uuid(), nullable=False),
    sa.Column('input_snapshot', sa.JSON(), nullable=True),
    sa.Column('model_info', sa.JSON(), nullable=True),
    sa.Column('token_usage', sa.JSON(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trip_generation_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trip_generation_runs_trip_id'), ['trip_id'], unique=False)

    op.create_table('usage_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('trip_id', sa.Uuid(), nullable=True),
    sa.Column('event_name', sa.Text(), nullable=False),
    sa.Column('event_props', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usage_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usage_events_trip_id'), ['trip_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_events_user_id'), ['user_id'], unique=False)

    op.create_table('chat_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('thread_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('target_ref_type', sa.Text(), nullable=True),
    sa.Column('target_ref_id', sa.Uuid(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('context_snapshot', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['thread_id'], ['chat_threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_messages_thread_id'), ['thread_id'], unique=False)

    op.create_table('plan_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('trip_day_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('time_block', sa.Text(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('cost_hint', sa.Text(), nullable=True),
    sa.Column('location_name', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('external_url', sa.Text(), nullable=True),
    sa.Column('maps_url', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('saved', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['trip_day_id'], ['trip_days.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plan_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plan_items_trip_day_id'), ['trip_day_id'], unique=False)

    op.create_table('trip_edits',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('trip_id', sa.Uuid(), nullable=False),
    sa.Column('thread_id', sa.Uuid(), nullable=True),
    sa.Column('user_message_id', sa.Uuid(), nullable=True),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('target_ref_type', sa.Text(), nullable=True),
    sa.Column('target_ref_id', sa.Uuid(), nullable=True),
    sa.Column('instruction', sa.Text(), nullable=True),
    sa.Column('result_summary', sa.Text(), nullable=True),
    sa.Column('diff', sa.JSON(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['thread_id'], ['chat_threads.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_message_id'], ['chat_messages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trip_edits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trip_edits_trip_id'), ['trip_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip_edits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trip_edits_trip_id'))

    op.drop_table('trip_edits')
    with op.batch_alter_table('plan_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plan_items_trip_day_id'))

    op.drop_table('plan_items')
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_messages_thread_id'))

    op.drop_table('chat_messages')
    with op.batch_alter_table('usage_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usage_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_usage_events_trip_id'))

    op.drop_table('usage_events')
    with op.batch_alter_table('trip_generation_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trip_generation_runs_trip_id'))

    op.drop_table('trip_generation_runs')
    with op.batch_alter_table('trip_days', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trip_days_trip_id'))

    op.drop_table('trip_days')
    with op.batch_alter_table('stay_options', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stay_options_trip_id'))

    op.drop_table('stay_options')
    with op.batch_alter_table('price_alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_price_alerts_user_id'))
        batch_op.drop_index(batch_op.f('ix_price_alerts_trip_id'))

    op.drop_table('price_alerts')
    with op.batch_alter_table('notification_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_notification_events_trip_id'))

    op.drop_table('notification_events')
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoices_user_id'))

    op.drop_table('invoices')
    with op.batch_alter_table('flight_options', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flight_options_trip_id'))

    op.drop_table('flight_options')
    with op.batch_alter_table('chat_threads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_threads_trip_id'))

    op.drop_table('chat_threads')
    op.drop_table('user_preferences')
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trips_user_id'))

    op.drop_table('trips')
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_user_id'))

    op.drop_table('subscriptions')
    op.drop_table('notification_preferences')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
